#!/usr/bin/env bash

if command -v stow >/dev/null; then
    git pull --quiet --recurse-submodules
    for dir in */; do
        stow -nt "$HOME" "$dir" 2>&1 | grep "^\s" | awk 'NF>1{print $NF}' | xargs -I{} rm -f "$HOME/{}"
        stow -t "$HOME" "$dir"
    done
else
    echo "GNU Stow is not found, files will be copied to \$HOME instead."
    read -rep "Continue with install? [y/N] " install
    [ "$install" = "${install#[Yy]}" ] && return
    git pull --quiet --recurse-submodules
    for dir in */; do
        cp -rfT "$dir" "$HOME"
        rm -f "$HOME/.git" 2>/dev/null
    done
fi
