#!/usr/bin/env bash

for dir in */; do
    if command -v stow >/dev/null; then
        stow -Dt "$HOME" "$dir"
    else
        find "$dir" -mindepth 1 ! -type d | while read -r del; do
            rm -f "${del/$dir/$HOME}"
        done
        find "$dir" -mindepth 1 -type d | tac | while read -r del; do
            [ -z "$(ls -A "${del/$dir/$HOME}" 2>/dev/null)" ] && \
                rm -rf "${del/$dir/$HOME}"
        done
    fi
done
